### ISSUE TITLE
nazewnictwo

### ISSUE THREAD

**Issue by lsiedlaczek** [patryk-wlaz/JS-skill#1]
prosze uzywaj polskich nazw

**Comment by patryk-wlaz** [comment]
Nie rozumiem, chodzi o zmienną hasztag? Żeby nazwać ją kratka, czy co? Czy
to raczej ogólna uwaga, nie dotycząca pierwszego ćwiczenia?
Zmieniać teraz wszystkie nazwy zmiennych, czy po prostu od dzisiaj używać
polskich słów?

2015-10-18 18:40 GMT+02:00 lsiedlaczek <notifications@github.com>:

**Comment by lsiedlaczek** [comment]
kurwa. angielskich . jebnalem sie ;)
variable, nazwy funkcji, wszystko po angielsku.

**Comment by patryk-wlaz** [comment]
A no to ok :) hehe
