### ISSUE TITLE
fizzbuzz

### ISSUE THREAD

**Issue by lsiedlaczek** [patryk-wlaz/JS-skill#11]
zle - w ogole nie jest czyste to Twoje rozwiazanie. pomysl dalej.
pomysl o laczeniu stringow w zaleznosci od warunkow.

**Comment by patryk-wlaz** [comment]
Zobacz teraz. Co to znaczy, że rozwiązanie jest nieczyste?

2015-10-21 12:39 GMT+02:00 lsiedlaczek <notifications@github.com>:

**Comment by lsiedlaczek** [comment]
poszedles w bardzo zla strone. tak ze nawet nie wiem jak Cie nakierowac, wiec moze podam dobre rozwiazanie

```javascript
function fizzBuzz(n) {
  var result;
  for (var i = 0; i <= n; i++) {
    result = '';
    if (i % 3 === 0) { result += "Fizz"; }
    if (i % 5 === 0) { result += "Buzz"; }
    console.log(result || i);
  }
}
```

przeanalizuj kod i zastanow sie czyj jest czytelniejszy - moj czy Twoj.

**Comment by patryk-wlaz** [comment]
Bardzo sprytne, faktycznie ładniej wygląda niż każde z moich rozwiązań.

2015-10-22 9:44 GMT+02:00 lsiedlaczek <notifications@github.com>:

**Comment by lsiedlaczek** [comment]
po prostu poszedles w zla strone, dont worry. bedzie tylko lepiej :)

**Comment by patryk-wlaz** [comment]
Ok dzięki ;)
