### ISSUE TITLE
7

### ISSUE THREAD

**Issue by lsiedlaczek** [patryk-wlaz/JS-skill#21]
wyrzuc prosze niepotrzebny kod z tych plikow.

**Comment by patryk-wlaz** [comment]
Ok, już.
Chciałem Ci dać kod nadający się do sprawdzenia (jak poprzednio chciałeś).
Nie miałem możliwości wstawienia kodu do animateWorld

2015-11-09 15:52 GMT+01:00 lsiedlaczek <notifications@github.com>:
